### ISSUE TITLE
Anlegen Datenbank für Material und durchgeführte Arbeiten

### ISSUE THREAD

**Issue by einsacknuesse** [SteMaker/AndroidArbeitsbericht#38]
Es wäre eine große Hilfe, wenn Listen für Material und durchgeführte Arbeiten erstellt würden, sodass häufig verwendetes Material/ häufig durchgeführte Arbeiten mit einem Klick ausgewählt werden können. Eine solche Liste wird zwar bereits erstellt, bei Beenden der App wird sie allerdings gelöscht.

**Comment by SteMaker** [comment]
@einsacknuesse Das klingt eher nach einem bug. Die vorher verwendeten Materialen und Arbeiten werden in einer Datei gespeichert und sollten beim nächsten Start auch wieder verfügbar sein. Sobald man ein paar Buchstaben eingegeben hat, sollte eine Vorschlagsliste erscheinen. Ich schau mir das an.

**Comment by SteMaker** [comment]
Das Problem ist, dass die Einstellungsdatei manchmal verloren gegangen ist. Sollte mit v2.21.0 behoben sein.
